version: "3.8"
services:
  web:
    build: ./
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
     - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:12.9-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  postgres_data: