# Generated by Django 4.2.13 on 2024-06-02 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
