# Generated by Django 4.2.13 on 2024-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_friendrequest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
